### ISSUE TITLE
Bag of Gold 4.5.3 bug

### ISSUE THREAD

**Issue by princemorii** [Rocologo/BagOfGold#141]
Hi,
Just updated all 3 plugins and this shows in the console. Using Paper 448 [1.19.3]

Error: https://pastebin.com/1aVkz3ZV

As well as latest mobhunting with latest CMIlib [21:40:00 INFO]: [MobHunting][Error] MobHunting could not register with [CMILib] please check if [CMILib] is compatible with the server [1.19.3-R0.1-SNAPSHOT]

**Comment by Rocologo** [comment]
It's look like you are upgrading from an old version?

**Comment by princemorii** [comment]
> It's look like you are upgrading from an old version?

Yes, do I have to delete the whole folder and start again?

**Comment by Rocologo** [comment]
Not normally. If you delete the bagofgold.db file you will keep your settings.

**Comment by princemorii** [comment]
> Not normally. If you delete the bagofgold.db file you will keep your settings.

I have deleted the whole folder just to test it it, I get this error even with a clean folder

https://pastebin.com/RXWESQ5N

& this for mob hunting with a clean folder
https://pastebin.com/mA32iyd0

**Comment by Rocologo** [comment]
Ohh I forgot that the config.yml contains a database_version setting. Try setting the version to 0 or delete it from your config.yml files and then restart the server. 

0 means that the plugin will try to detect the database version, and since the db file is deleted, it should create a new empty db.

**Comment by princemorii** [comment]
> database_version

Even with a new DB,

BofG: https://pastebin.com/PjVbnC0G
MobH: https://pastebin.com/sb2vxZeF

**Comment by Rocologo** [comment]
What is the database_version number?

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: ***@***.***>
Sendt: 11. april 2023 15:34
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [Rocologo/BagOfGold] Bag of Gold 4.5.3 console error (Issue #141)


database_version

Even with a new DB,

BofG: https://pastebin.com/PjVbnC0G
MobH: https://pastebin.com/sb2vxZeF

**Comment by princemorii** [comment]
> What is the database_version number?

bag of gold is 3
mobhunting is 7

**Comment by Rocologo** [comment]
BagOfGold should be 4 ??? Try changing the value to 4 when the server is not running.

**Comment by Rocologo** [comment]
My guess is that the developer of CMILib has changed something in his library. I will see If I can get some time tomorrow evenung to fix this problem.

**Comment by Rocologo** [comment]
Today i fixed a MySQL bug. ANd the I realized that I forgot to check CMI/CMILIB so I did this. I works om my server, so I need more information.

[16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling CustomItemsLib v1.0.6
[16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Loading config.yml file, version -1
[16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Loaded 34 rewards from the CustomItemsLib/rewards.yml file
[16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Initialize database
[16:05:45] [BGC TaskThread/INFO]: [CustomItemsLib][Debug] Saving CustomItemsLib data
[16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with ProtocolLib (5.0.0-SNAPSHOT-b632).
[16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with TitleManager (2.3.5)
[16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with CMI (9.5.0.6).
[16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with CMILib (1.2.5.3).
[16:05:45] [Server thread/INFO]: [CustomItemsLib] CustomItemsLib is using EssentialsX Economy via Vault as Economy Provider
[16:05:45] [Server thread/INFO]: [BagOfGold] Enabling BagOfGold v4.5.4
[16:05:45] [Server thread/INFO]: [BagOfGold] Config.yml was backed up to plugins/BagOfGold/backup/config.yml.bak15
[16:05:45] [Server thread/INFO]: [BagOfGold][Debug] bStat is enabled
[16:05:45] [Server thread/INFO]: [BagOfGold][Debug] Initialize database
[16:05:45] [Server thread/INFO]: [BagOfGold][Debug] Loading banks.yml
[16:05:45] [Server thread/INFO]: [BagOfGold][Debug] 2 banks was loaded from BagOfGold/banks.yml
[16:05:45] [BG TaskThread/INFO]: [BagOfGold][Debug] Saving BagOfGold data
[16:05:45] [BG TaskThread/INFO]: [BagOfGold][Debug] Saved 2 Banks to disk
[16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with PerWorldInventory (2.3.2)
[16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Citizens2 (2.0.31-SNAPSHOT (build 3023))
[16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Essentials (2.20.0-dev+54-384f63b)
[16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with FastAsyncWorldEdit (2.6.0-SNAPSHOT-399;da4d966)
[16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with WorldGuard (7.1.0-SNAPSHOT+2232-b67fd01)
[16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with PlaceholderAPI (2.11.3).
[16:05:45] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bagofgold [1.0.0]
[16:05:45] [Server thread/INFO]: [BagOfGold][Debug] PlaceHolderManager started
[16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Shopkeepers (2.16.1)

**Comment by princemorii** [comment]
> Today i fixed a MySQL bug. ANd the I realized that I forgot to check CMI/CMILIB so I did this. I works om my server, so I need more information.
> 
> [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling CustomItemsLib v1.0.6 [16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Loading config.yml file, version -1 [16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Loaded 34 rewards from the CustomItemsLib/rewards.yml file [16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Initialize database [16:05:45] [BGC TaskThread/INFO]: [CustomItemsLib][Debug] Saving CustomItemsLib data [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with ProtocolLib (5.0.0-SNAPSHOT-b632). [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with TitleManager (2.3.5) [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with CMI (9.5.0.6). [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with CMILib (1.2.5.3). [16:05:45] [Server thread/INFO]: [CustomItemsLib] CustomItemsLib is using EssentialsX Economy via Vault as Economy Provider [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling BagOfGold v4.5.4 [16:05:45] [Server thread/INFO]: [BagOfGold] Config.yml was backed up to plugins/BagOfGold/backup/config.yml.bak15 [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] bStat is enabled [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] Initialize database [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] Loading banks.yml [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] 2 banks was loaded from BagOfGold/banks.yml [16:05:45] [BG TaskThread/INFO]: [BagOfGold][Debug] Saving BagOfGold data [16:05:45] [BG TaskThread/INFO]: [BagOfGold][Debug] Saved 2 Banks to disk [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with PerWorldInventory (2.3.2) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Citizens2 (2.0.31-SNAPSHOT (build 3023)) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Essentials (2.20.0-dev+54-384f63b) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with FastAsyncWorldEdit (2.6.0-SNAPSHOT-399;da4d966) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with WorldGuard (7.1.0-SNAPSHOT+2232-b67fd01) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with PlaceholderAPI (2.11.3). [16:05:45] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bagofgold [1.0.0] [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] PlaceHolderManager started [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Shopkeepers (2.16.1)

It is possible that the newer version of CMILib is fixed, since your using one version ahead. I will test with the newest and let you know. Also it was regarding MobHunting not BagOfGold. I will report back soon. Thank you

**Comment by princemorii** [comment]
> Today i fixed a MySQL bug. ANd the I realized that I forgot to check CMI/CMILIB so I did this. I works om my server, so I need more information.
> 
> [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling CustomItemsLib v1.0.6 [16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Loading config.yml file, version -1 [16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Loaded 34 rewards from the CustomItemsLib/rewards.yml file [16:05:45] [Server thread/INFO]: [CustomItemsLib][Debug] Initialize database [16:05:45] [BGC TaskThread/INFO]: [CustomItemsLib][Debug] Saving CustomItemsLib data [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with ProtocolLib (5.0.0-SNAPSHOT-b632). [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with TitleManager (2.3.5) [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with CMI (9.5.0.6). [16:05:45] [Server thread/INFO]: [CustomItemsLib] Enabling compatibility with CMILib (1.2.5.3). [16:05:45] [Server thread/INFO]: [CustomItemsLib] CustomItemsLib is using EssentialsX Economy via Vault as Economy Provider [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling BagOfGold v4.5.4 [16:05:45] [Server thread/INFO]: [BagOfGold] Config.yml was backed up to plugins/BagOfGold/backup/config.yml.bak15 [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] bStat is enabled [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] Initialize database [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] Loading banks.yml [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] 2 banks was loaded from BagOfGold/banks.yml [16:05:45] [BG TaskThread/INFO]: [BagOfGold][Debug] Saving BagOfGold data [16:05:45] [BG TaskThread/INFO]: [BagOfGold][Debug] Saved 2 Banks to disk [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with PerWorldInventory (2.3.2) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Citizens2 (2.0.31-SNAPSHOT (build 3023)) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Essentials (2.20.0-dev+54-384f63b) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with FastAsyncWorldEdit (2.6.0-SNAPSHOT-399;da4d966) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with WorldGuard (7.1.0-SNAPSHOT+2232-b67fd01) [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with PlaceholderAPI (2.11.3). [16:05:45] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bagofgold [1.0.0] [16:05:45] [Server thread/INFO]: [BagOfGold][Debug] PlaceHolderManager started [16:05:45] [Server thread/INFO]: [BagOfGold] Enabling compatibility with Shopkeepers (2.16.1)

on MobHunting latest version, and CMIILib latest version, I still get this:
 [MobHunting][Error] MobHunting could not register with [CMILib] please check if [CMILib] is compatible with the server [1.19.3-R0.1-SNAPSHOT]

**Comment by Rocologo** [comment]
Could you please enable debugging "/bag debug", start the server and give me a complete server.log so I can see what happens.
