### ISSUE TITLE
Shopkeeper bug

### ISSUE THREAD

**Issue by Rocologo** [Rocologo/BagOfGold#146]
@MuYuehe has found this bug (https://github.com/MuYuehe)

When he opens Shopkeeper GUI in edit mode. 

https://pastebin.com/3AfVpFEC]

**Comment by MuYuehe** [comment]
Thanks for adding a new issue. My suggestion is to temporarily compile the shopkeepers configuration file in `data/save.yml` to edit the store

**Comment by Rocologo** [comment]
This bug should be fixed in newest SNAPSHOT 

https://jenkins.lindegaard.one/job/CustomItemsLib/

**Comment by MuYuehe** [comment]
It doesn't look like it's fully fixed.
Sorry, I can still reproduce this error.
> [11:52:03] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CustomItemsLib v1.0.9-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2783) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "isCurrentSlot" is null
        at one.lindegaard.CustomItemsLib.rewards.CoreRewardListeners.onInventoryClickReward(CoreRewardListeners.java:835) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 20 more

**Comment by Rocologo** [comment]
I found another error so please test again https://jenkins.lindegaard.one/job/CustomItemsLib/

Also in this build I have changed how the plugin works when hold more money in your hand. This means that you can press "COLLECT_ALL_TO_CURSOR" by double clicking a bag. This way you will be able to collect a big amount of money in your hand, but when you the press "PLACE_SOME" or "PLACE_ALL" you will only place the limit-bag-size in the slot and keep the rest in your hand. I hope you understand what I mean.
