### ISSUE TITLE
Gold lost while depositing, again

### ISSUE THREAD

**Issue by braceyourself07** [Rocologo/BagOfGold#42]
Player received gold, deposited in bank, but did not change bank balance and now has 0 gold in hand.

https://pastebin.com/6vFFeex8

Screenshot https://i.imgur.com/eTLJ0g4.png

BagofGold v2.0.9-SNAPSHOT-B163
MobHunting v6.0.7-SNAPSHOT-B718

Arcaniax (player affected) said that another player got the 64k from mob drops who then gave it to him.

**Comment by Rocologo** [comment]
The log is very usefull i see where its goes wrong

[06:13:30] [Server thread/INFO]: [BagOfGold][Debug] Check if Arcaniax has 66185.93 Gold on the balance=66185.93)
[06:13:30] [Server thread/INFO]: [BagOfGold][Debug] Arcaniax has not enough bagofgold, Withdrawing only 66185.93 , new balance is 0

So now I know where to look to hopefully find the bug. :-)

**Comment by Rocologo** [comment]
Fixed in v2.1.0 I hope :-)

**Comment by braceyourself07** [comment]
I believe it is still happening.  This player accumulated 680 gold while killing mobs, went to deposit and then his personal balance became 0 and his bank balance remain unchanged.

https://pastebin.com/5Ug8eADZ

**Comment by Rocologo** [comment]
Yes i see the money is missing on the bank balance i will study the code again

**Comment by Rocologo** [comment]
Do you know if DJjux is a brand new player on your server?

**Comment by braceyourself07** [comment]
DJjux has been playing since the server opened last month. But good that some other issues were revealed and fixed! I'll add the update and report back as any issues come up.
