### ISSUE TITLE
Using bagofgold bag top, i see only staff.

### ISSUE THREAD

**Issue by kelso6969** [Rocologo/BagOfGold#52]
Using as a non-staff account, you see everyone, but numbers are very inconsistent. Sometimes it displays right, other times not so much. Using latest essentials 2.16.3 and latest BOG.

**Comment by Rocologo** [comment]
Which command do you use?

**Comment by kelso6969** [comment]
bagofgold bag top

I've mad an alias for baltop since it seems to report different numbers.

**Comment by Rocologo** [comment]
Please notice that the top command show total wealth (balance + bank balance)

I think I have fixed the problem now. Please help me with the testing, try build 185 

https://fractal.lindegaard.one:8181/job/BagOfGold/

**Comment by kelso6969** [comment]
looking better, thank you.

I have another issue open about an error spamming console, still getting that one. Will add latest console spam to that ticket.

**Comment by Rocologo** [comment]
Perfect. Thank you posting the update error text, this helps me a lot.
