### ISSUE TITLE
Bugs with  drop-money-on-ground-itemtype set as ITEM ?

### ISSUE THREAD

**Issue by Pumpk1in** [Rocologo/BagOfGold#90]
Hi @Rocologo 

You'll find a copy/paste from my forum post bellow.

But as you anwered about "gringotts_style" mode, I have a question : ITEM mode do not support split and stacks ? Only gringotts_style supports it ?

Also, you have to know that I decided to switch from SKULLS to ITEMS because I had problems with shopkeepers (works with citizens). It works with money items (default; emerald), and I was not able to make it work with SKULLS. If you have an idea for that it would be nice !

The original post : 

Until now, I used Bagsofgold with drop-money-on-ground-itemtype: SKULL, no problem at all with that.

Now I want to use it with the emerald as ITEM.
And a lot of things are not working anymore.

- can't stack given/withdrawn emeralds to make a bigger emerald "bag"
- - tested creative & survival
- can't split given/withdrawn emeralds to have two emerald with lower values
- - tested creative & survival
- can't deposit to the bank at all (console spam error bellow)
- can't withdraw from the bank if you already have ONE emerald in your inventory
- Your money is duplicated, each time you open inventory if you are in creative.
- - This is a old bug that does not happen anymore with the skulls If i'm correct

I never tried your plugin with an item before, is it the normal behaviour ? :oops:
If not, there is a lot of bugs right there.

Thanks !

Some errors in console 
`[14:56:51] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BagOfGold v2.9.2
java.lang.IllegalArgumentException: Invalid UUID string:
    at java.util.UUID.fromString(UUID.java:215) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.Reward.setReward(Reward.java:136) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.Reward.<init>(Reward.java:81) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.Reward.getReward(Reward.java:371) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.getSpaceForBagOfGoldMoney(BagOfGoldItems.java:347) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.RewardManager.getSpaceForMoney(RewardManager.java:569) ~[?:?]
    at one.lindegaard.BagOfGold.bank.BankSign.onPlayerInteractEvent(BankSign.java:156) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor119.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-143]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
    at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
    at java.lang.Thread.run(Thread.java:834) [?:?]
[15:00:44] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to BagOfGold v2.9.2
java.lang.IllegalArgumentException: Invalid UUID string:
    at java.util.UUID.fromString(UUID.java:215) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.Reward.setReward(Reward.java:136) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.Reward.<init>(Reward.java:81) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.Reward.getReward(Reward.java:371) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.BagOfGoldItems.getAmountOfBagOfGoldMoneyInInventory(BagOfGoldItems.java:279) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.RewardManager.getAmountInInventory(RewardManager.java:401) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.RewardManager.adjustPlayerBalanceToAmounOfMoneyInInventory(RewardManager.java:535) ~[?:?]
    at one.lindegaard.BagOfGold.rewards.RewardListeners.onInventoryCloseEvent(RewardListeners.java:39) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor113.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-143]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
    at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1375) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.PlayerList.disconnect(PlayerList.java:407) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.NetworkManager.handleDisconnection(NetworkManager.java:356) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:163) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
    at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Rocologo** [comment]
It is very rare that I test the type ITEM most people use SKULL or the GRINGOTTS_STYLE So yo might have found a bug, or I have introduced a bug since last time i tested ITEM.

I have never tested Shopkeepers so I don't know. There is alot of Inventory Shops out there and I think they all have a problem with BagOfGold because the see the Bag as SKULL and not as a valued item. I think you should try to contact the dev of Shopkepper and ask him to make support for the BagOfGold Economy plugin.

**Comment by Rocologo** [comment]
My best guess is that Shopkeeper would have problem with ITEM as well, because it would not be able to see the value of the item unless he adds support for BagOfGold

**Comment by Rocologo** [comment]
I will test ITEM but you should still contact the dev of Shopkeeper

**Comment by Rocologo** [comment]
I think I found the bug, when you use ITEMS. It should work now, incl. splitting and merging money items.

This newest build
https://fractal.lindegaard.one:8181/job/BagOfGold/

Let me know how it works.

**Comment by Pumpk1in** [comment]
> I think I found the bug, when you use ITEMS. It should work now, incl. splitting and merging money items.
> 
> This newest build
> https://fractal.lindegaard.one:8181/job/BagOfGold/
> 
> Let me know how it works.

Yep it works ! Also the bank works again too.
The duplicate problem is still there in creative but as you did not mention that, it seems logical ! :)

About Shopkeepers, well, maybe we will have to work with another plugin.
(The description said he will not make that kind of compatibility work.)

**Comment by Rocologo** [comment]
yes it was a long post ... I didnt see the creative bug. I will fix it now.

**Comment by Rocologo** [comment]
Hmmm this one is NOT easy... it works when ProtocolLib is not loaded, but it does not work (always) work when ProtocolLib is loaded

**Comment by Rocologo** [comment]
I think this is fixed in next release :-)
